#!/bin/bash

# Adds and removes files just with a partial name.


# Dot special case
if [[ $# = 1 && $1 = '.' ]]; then
	git status --porcelain | cut -c 4- | xargs -L 1 gad
	exit $?
fi


# Normal case

# Find the file with gick
fileFound=`gick $@ 2>/dev/null`

if [[ $? != 0 ]]; then
	echo 'No file found' >&2
	exit 1
fi

# Retrieve both status of the file
fileStatus=`git status --short $fileFound`
indexStatus=${fileStatus:0:1}
workStatus=${fileStatus:1:1}

case $workStatus in
	' ')
		case $indexStatus in
			[MA])
				echo "Already staged '$fileFound'" >&2
				;;
			'D')
				echo "Already removed '$fileFound'" >&2
				;;
			esac
		;;
	[MA?])
		git add -v $fileFound
		;;
	[D])
		git rm $fileFound
		;;
	*)
		echo "Unknown status '$workStatus'" >&2
		echo 'Nothing done' >&2
		;;
esac

