#!/bin/bash

# Unstages a file found with gick.


# Dot special case, reset everything
if [[ $# = 1 && $1 = '.' ]]; then
	git status --porcelain | cut -c 4- | xargs -L 1 geset
	exit $?
fi

# Normal case
fileFound=`gick $@ 2>/dev/null`

if [ $? -ne 0 ]; then
	echo 'No file found'
	exit 1
fi

echo reset \'$fileFound\'
git reset HEAD --quiet $fileFound

