#!/bin/bash

# Prings the first matching line from the git remote branches and cuts
# the "origin/" part of it

if [ $# -le 0 ]; then
	echo 'No branch found' >&2
	exit 1
fi

git branch -r | cut -c 10- | grep --max-count 1 $@

