#!/bin/bash

# Prints the first matching line from the git branches

# By default it seeks for a match in the local branches, if -r is
# provided, it prints the first matching branch on remote branches. 

params=`getopt r $*`
getoptStatus=$?
set -- $params

if [[ $getoptStatus != 0 ]]; then
	echo 'Invalid options' >&2
	exit 1
fi

useRemotes=''

for param; do
	case "$param" in
		-r)
			useRemotes='-r'
			shift;;
		--)
			shift; break;;
	esac
done

if [[ $# = 0 ]]; then
	echo 'No parameters given' >&2
	exit 2
fi

git branch $useRemotes | tr -d [:blank:] | tr -d '*' | pick $@

