#!/bin/bash

# Using the pick command prints the matching files that appear in git status.

# gick will only check for the -w option with which it will ignore any files
# that only have a staging status, thus only files that have workspace changes
# will be considered.

# Any other option passed to gick is passed through to pick.

if [[ $# = 0 ]]; then
	echo 'No parameters given' >&2
	exit 1
fi

if [[ $1 = '-w' ]]; then
	shift;
	# Ignores any files without workspace status
	# TODO this can be an option in gtatus
	fileList=$(gtatus | grep --invert-match '^. ' | cut -c 4-)
else
	fileList=$(gtatus -c)
fi

# OSX and other NIX have different option for extended regex
if [[ $(uname) == 'Darwin' ]]; then
	extendedOption="-E"
else
	extendedOption="-r"
fi

# Looks for " -> " and replaces it with a newline to split both paths
# TODO this should also come from gtatus, JESUS
fileList=$(echo "$fileList" | sed $extendedOption "s%(.*) -> (.*)%\1|\2%" | tr "|" "\n")

# When there are spaces in the filenames git surrounds them with quotes
# we dont want them here since we are splitting by line
# TODO also from gtatus, once -> files are also properly split....
fileList=$(echo "$fileList" | sed $extendedOption "s%^\"(.*)\"$%\1%")

# We search only in the filenames returned by status
matches=$(echo "$fileList" | pick "$@" 2>/dev/null)
if [[ $? != 0 ]]; then
	echo 'No files found' >&2
	exit 2
fi

echo "$matches"

