#!/bin/bash

read -d '' helpDoc <<"helpDoc"
NAME
    gickr -- search git remotes

SYNOPSIS
    gickr [-h] [--] [<substrings>...]

DESCRIPTION
    Prints the first matching git remote searching with `pick` and the
    given `<substrings>`.

    If there is only a single remote it will be printed when no
    `<substrings>` are given. When the repository has multiple remotes
    providing `<substrings>` is mandatory to perform the search.

OPTIONS
    -h  Prints this help output and quits the program.
helpDoc


# TODO add passtrhough options


# Error codes
error_invalidOptions=1
error_noArguments=2


# Options defaults
pickOptions=''


# Options parsing
while getopts :ha option; do
	case $option in
 		h)
			# Print help
			if [[ -t 0 ]]; then
				echo "$helpDoc" | less
			else
				echo "$helpDoc"
			fi
			exit 0
			;;
		[a])
			# Pass through to pick
			# all matches
			pickOptions+=" -$option"
			;;
		?)
            echo "Invalid option: -$OPTARG" >&2
			exit $error_invalidOptions
			;;
	esac
done
shift $(( OPTIND - 1 ));


# No arguments option
if [[ $# = 0 ]]; then
	count=$(git remote | wc -l | tr -d [:blank:])
	if [[ $count -eq 1 ]]; then
		git remote
		exit 0
	else
		echo 'No single remote found' >&2
		exit 1
	fi
fi

git remote | pick $pickOptions -- "$@"

