#!/bin/bash

read -d '' helpDoc <<"helpDoc"
NAME
    gick -- picks files from git status

SYNOPSIS
    pick [-hswdv] <substring>...

DESCRIPTION
    Using the pick command prints the first matching file that appears in
    git status. By default only the filename is printed.

OPTIONS
    -h  Prints this help output.
    
    -s  Considers only files with any status in stage.
    
    -w  Considers only files with any status in the workspace.
    
    -d  Consider dots as part of a regular expression, instead of escaping
        them.
    
    -v  Prints also the status of the matched file. The format remains the
        same as with git status --porcelain.
helpDoc


# Error codes
error_invalidOptions=1
error_noParams=2
error_noMatch=3


# Options values
gtatusOptions=''
pickOptions=''
showStatus='false'


# Options parsing
while getopts hwsdv option; do
	case $option in
 		h)
			# Print help
			if [[ -t 0 ]]; then
				echo "$helpDoc" | less
			else
				echo "$helpDoc"
			fi
			exit
			;;
		s|w)
			# Pass through to gtatus
			# Limit to stage or workspace
			gtatusOptions="$gtatusOptions -$option"
			;;
		d)
			# Pass through to pick
			# keep dots
			pickOptions="$pickOptions -$option"
			;;
		v)
			# Display status
			showStatus='true'
			;;
		?)
			exit $error_invalidOptions
			;;
	esac
done

shift $(( OPTIND - 1 ));


# Options validation
if [[ $# = 0 ]]; then
	echo 'No parameters given' >&2
	exit $error_noParams
fi


# List of files to consider
fileList=$(gtatus -c $gtatusOptions)

# Picking
matches=$(echo "$fileList" | pick $pickOptions -- "$@" 2>/dev/null)
if [[ $? != 0 ]]; then
	echo 'No match found' >&2
	exit $error_noMatch
fi

if [[ $showStatus = 'true' ]]; then
	gtatus -- "$matches"
else
	echo "$matches"
fi

