#!/bin/bash


read -d '' helpDoc <<"helpDoc"
# Prints matching branches using pick.

# By default it seeks for a match in the local branches, if -r is
# provided, it prints the first matching branch on remote branches.

# Options given after "--" will be passed directly to pick.
NAME
    gickb -- search through git branches

SYNOPSIS
    gickb [-hra] <substrings>...

DESCRIPTION
    Prints the first matching git branch searching with `pick` and the
    given substrings.

OPTIONS
    -h  Prints this help output.

    -r  Searches through remote branches, instead of local ones.

    -a  Prints all matches, instead of only the first one.
helpDoc


# Error codes
error_invalidOptions=1
error_noParams=2


# Options values
gitBranchOptions=''
pickOptions=''


# Options parsing
while getopts :hra option; do
	case $option in
 		h)
			# Print help
			if [[ -t 0 ]]; then
				echo "$helpDoc" | less
			else
				echo "$helpDoc"
			fi
			exit
			;;
		r)
			# Use remotes
			gitBranchOptions+=' -r'
			;;
		a)
			# Pass through for pick
			pickOptions+=" -$option"
			;;
		?)
            echo "Invalid option: -$OPTARG" >&2
			exit $error_invalidOptions
			;;
	esac
done

shift $(( OPTIND - 1 ));


# Options validation
if [[ $# = 0 ]]; then
	echo 'No parameters given' >&2
	exit $error_noParams
fi

# TODO check if branches can have spaces in their names, if so this wrong
git branch $gitBranchOptions | tr -d '*' | tr -d [:blank:] | pick $pickOptions -- "$@"

