#!/bin/bash

# Runs the gif script, followed with a gad of the same file.

fileFound=$(gick $@ 2> /dev/null)

if [[ $? != 0 ]]; then
	echo 'No file found' >&2
	exit 1
fi

echo "diff '$fileFound'"

echo 'Waiting for diff tool to return...'

git difftool --tool $GOOLS_DIFFTOOL --no-prompt HEAD $fileFound

read -p 'Git add? (y) ' addConfirm

if [ "$addConfirm" = 'y' ]; then
	gadd $@
else
	echo 'Aborted' >&2
	exit 1
fi

