#!/bin/bash

read -d '' helpDoc <<"helpDoc"
NAME
    giff -- runs git difftool using pick to select the file

SYNOPSIS
    giff [-hiup] <substring>...

DESCRIPTION
TODO update helpdoc
    Run a git difference using the first matching file found using gick
    -p if used as the first argument will prevent any matching to happen
    through gick, and next parameter will be interpreted as the file itself

    Always compares with head, unless -i is used.

OPTIONS
    -h  Prints this help output.

    -i  Compare files between stage and the workspace. Using this option
        takes precedence over `-u`.

    -u  Compare files between HEAD and stage.

    -p  Prints only the filenames, status are ommited.
helpDoc


# Error codes
error_invalidOptions=1
error_noParams=2
error_noMatch=3
error_noChanges=4


# Options values
usePlainPath='false'
compareStageAndWorkspace='false'
compareHeadAndStage='false'


# Options parsing
while getopts :hiup option; do
	case $option in
 		h)
			# Print help
			if [[ -t 0 ]]; then
				echo "$helpDoc" | less
			else
				echo "$helpDoc"
			fi
			exit
			;;
		i)
			# Compare between stage and workspace
			compareStageAndWorkspace='true'
			;;
		u)
			# Compare between head and stage
			compareHeadAndStage='true'
			;;
		p)
			# Use plain, do not pick
			usePlainPath='true'
			;;
		?)
			echo "Invalid option: -$OPTARG" >&2
			exit $error_invalidOptions
			;;
	esac
done

shift $(( OPTIND - 1 ));


# Options validation
if [[ $# = 0 ]]; then
	echo 'No parameters given' >&2
	exit $error_noParams
fi


if [[ $usePlainPath = 'true' ]]; then
	fileName="$1"
else
	fileName=$(gick "$@" 2> /dev/null | head -n 1)

	if [[ $fileName = '' ]]; then
		echo 'No file found' >&2
		exit $error_noMatch
	fi
fi

echo "diff '$fileName'"

# TODO if we can extract stage/head files to temporal location, running
# with -ui should open a three way compare BABY
difftoolOptions='--no-prompt --minimal --exit-code'
if [[ $compareStageAndWorkspace = 'true' ]]; then
	git difftool $difftoolOptions -- "$fileName"
	diffToolExit=$?
elif [[ $compareHeadAndStage = 'true' ]]; then
	git difftool $difftoolOptions --staged HEAD -- "$fileName"
	diffToolExit=$?
else
	git difftool $difftoolOptions HEAD -- "$fileName"
	diffToolExit=$?
fi

if [[ $diffToolExit = 0 ]]; then
	# TODO if a not existing file is provided with -p, 'no changes' is printed
	# need to check if a file exists and has status, maybe glist can do that
	echo 'No changes' >&2
	exit $error_noChanges
fi

