#!/bin/bash

# Run a git difference using the first matching file found using gick
# 
# -p if used as the first argument will prevent any matching to happen
# through gick, and next parameter will be interpreted as the file itself

fileFound=''

if [[ $1 = '-p' ]]; then
	fileFound="$2"
else
	fileFound=$(gick "$@" 2> /dev/null)
	
	if [[ $? != 0 ]]; then
		echo 'No file found' >&2
		exit 1
	fi
fi

# Get just the first file
fileFound="$(echo "$fileFound" | head -n 1)"
echo "diff '$fileFound'"
git difftool --minimal --no-prompt HEAD -- "$fileFound"
