#!/bin/bash

read -d '' helpDoc <<"helpDoc"
Displays helpfull information about the git repository
helpDoc


# Error codes
error_helpDoc=1
error_unknowInfo=2
error_noRemoteFound=3
error_notInABranch=4
error_noTrackingBranch=5


if [[ $# = 0 || $1 = '-h' || $1 = '--help' ]]; then
	echo "$helpDoc" >&2
	exit $error_helpDoc
fi

case $1 in
	url|urls)
		# remove the "url" subcommand
		shift
		
		remotes=$(gickr $@ 2> /dev/null)
		if [[ $? != 0 ]]; then
			echo 'No remote found' >&2
			exit $error_noRemoteFound
		fi
		
		git remote show -n $remotes
		exit
		;;
		
	user)
		echo $(git config user.name) $(git config user.email)
		;;
		
	branch)
		branchRef=$(git symbolic-ref HEAD 2>/dev/null)
		if [[ $? != 0 ]]; then
			echo 'Not in a branch' >&2
			exit $error_notInABranch
		fi
		# Removing the initial "refs/heads/"
		echo ${branchRef#refs/heads/}
		;;
		
	tracking|upstream)
		upstream=$(git rev-parse --symbolic-full-name @{upstream} 2>/dev/null)
		if [[ $? != 0 ]]; then
			echo 'No tracking branch' >&2
			exit $error_noTrackingBranch
		fi
		
		# Removing the initial "refs/remotes/""
		echo ${upstream#refs/remotes/}
		;;
		
	*)
		echo 'Unknown info' >&2
		exit $error_unknowInfo
		;;
esac

