#!/bin/bash

read -d '' helpDoc <<"helpDoc"
NAME
    gout -- checks out a branch selected with `gickb`

SYNOPSIS
    gout [-hr] [--] <substrings>...

DESCRIPTION
    Checks out a local branch selected with `gickb` and the given
    `<substrings>`.

OPTIONS
    -h  Prints this help output and quits the program.

    -r  Searches through remote branches, instead of local.
helpDoc


# Error codes
error_invalidOptions=1
error_noMatches=2
error_ambiguousMatch=3


# Options defaults
useRemote='false'
gickbOptions=''


# Options parsing
while getopts :hr option; do
	case $option in
 		h)
			# Print help
			if [[ -t 0 ]]; then
				echo "$helpDoc" | less
			else
				echo "$helpDoc"
			fi
			exit 0
			;;
		r)
			# Searches remote branches
			useRemote='true'
			gickbOptions+=' -r'
			;;
		?)
			echo "Invalid option: -$OPTARG" >&2
			exit $error_invalidOptions
			;;
	esac
done
shift $(( OPTIND - 1 ));


# Always get all matching branches with -a
branches=$(gickb -a $gickbOptions -- "$@" 2>/dev/null)

if [[ $? != 0 ]]; then
	echo 'No branch found' >&2
	exit $error_noMatches
fi

matchesCount=$(echo "$branches" | wc -l | tr -d [:blank:])
if [[ $matchesCount > 1 ]]; then
	echo 'Ambiguous branch match' >&2
	echo "$branches" >&2
	exit $error_ambiguousMatch
fi

# Otherwise there is single branch
branchName=$branches

# Clean up remote
if [[ $useRemote = 'true' ]]; then
	branchName=${branchName#*/}
fi

git checkout "$branchName"

