#!/bin/bash

# Checkout a remote branch found through gickbranch

branchMatch=`gickbranch -r $@ 2>/dev/null`

if [[ $? != 0 ]]; then
	echo 'No branch found' >&2
	exit 1
fi

read -p "Switch to branch '$branchMatch'? (y) " switchConfirm

if [[ $switchConfirm = 'y' ]]; then
	branchMatch=${branchMatch#*/}
	echo "Switching to branch '$branchMatch'"
	git checkout $branchMatch
else
	echo 'Aborted' >&2
	exit 1
fi

