#!/bin/bash

# Pushes and set the upstream of a branch to a remote branch of the
# same name.

# If only a single remote is defined for the repository it is used
# by default. If more that one exists the given parameters will be
# used to pick form the available remotes.


# Check if there is a default remote (or pick one)
if [[ $# = 0 ]]; then
	# Must have a default remote
	remote=`gremote 2>/dev/null`
	if [[ $? != 0 ]]; then
		echo 'No default remote branch' >&2
		exit 1
	fi
else
	# Pick a remote
	remote=`gremote $@ 2>/dev/null`
	if [[ $? != 0 ]]; then
		echo 'No remote match found' >&2
		exit 2
	fi
fi

# Check the name of the current branch
branchName=`granch`
if [[ $? != 0 ]]; then
	exit 3
fi

# Check the branch does not exists remotely
remoteBranchName="$remote/$branchName"
git branch -r | cut -c 3- | grep "^$remoteBranchName$" >/dev/null
if [[ $? = 0 ]]; then
	echo "Remote branch already exists '$remoteBranchName'" >&2
	exit 4
fi

# All good so beam it up
git push -u $remote $branchName

